.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "DIFFSHIPPER" "1" "January 2013" "" ""
.
.SH "NAME"
\fBdiffshipper\fR \- Floobits diff shipper\. The mediocre fall\-back solution for people with unsupported editors\.
.
.SH "SYNOPSIS"
\fBdiffshipper \-r ROOM_NAME \-o ROOM_OWNER \-u USERNAME \-s API_SECRET [OPTIONS] PATH\fR
.
.SH "DESCRIPTION"
Join a Floobits room and monitor files in PATH for changes\.
.
.SH "OPTIONS"
.
.IP "\(bu" 4
\fB\-\-api\-url URL\fR For debugging/development\. Defaults to https://floobits\.com/api/room/
.
.IP "\(bu" 4
\fB\-\-create\-room\fR Create a room and add PATH
.
.IP "\(bu" 4
\fB\-\-delete\-room\fR Delete a room\. Can be used with \-\-create\-room\.
.
.IP "\(bu" 4
\fB\-D\fR Enable debug output
.
.IP "\(bu" 4
\fB\-h HOST\fR For debugging/development\. Defaults to floobits\.com\.
.
.IP "\(bu" 4
\fB\-o OWNER\fR Room owner
.
.IP "\(bu" 4
\fB\-p PORT\fR For debugging/development\. Defaults to 3148\.
.
.IP "\(bu" 4
\fB\-r ROOMNAME\fR Room to join
.
.IP "\(bu" 4
\fB\-\-recreate\-room\fR Delete the room if it exists, then create it again
.
.IP "\(bu" 4
\fB\-\-room\-perms PERM\fR Used with \-\-[re]create\-room\. 0 = private, 1 = readable by anyone, 2 = writeable by anyone
.
.IP "\(bu" 4
\fB\-s SECRET\fR API secret
.
.IP "\(bu" 4
\fB\-u USERNAME\fR Username
.
.IP "\(bu" 4
\fB\-v\fR Print version and exit
.
.IP "" 0
.
.SH "EXAMPLES"
\fBdiffshipper \-r testroom \-o myuser \-u myuser \-s ve3aiCoo ~/code/collab_project/\fR
.
.P
Join https://floobits\.com/r/myuser/testroom/ and keep files in ~/code/collab_project/ synced with that room\.
